server:
  servlet:
    context-path: /tweets-consumer

spring:
  datasource:
    url: jdbc:h2:mem:tweetsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true    
      path: /h2
      
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,shutdown
